publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string" }
          - { label: "Intro Heading", name: "introHeading", widget: "string" }
          - { label: "Intro Paragraph 1", name: "introParagraph1", widget: "text" }
          - { label: "Intro Paragraph 2", name: "introParagraph2", widget: "text" }
          - { label: "Meet The Team Heading", name: "meetTeamHeading", widget: "string" }
          - { label: "Meet The Team Subheading", name: "meetTeamSubHeading", widget: "string" }
          - { label: "Meet The Team Paragraph", name: "meetTeamParagraph", widget: "text" }
          - { label: "Final Slogan", name: "finalSlogan", widget: "text" }
          - { label: "Book Now Button", name: "bookNowButton", widget: "string" }
          - { label: "About Button", name: "aboutButton", widget: "string" }
          - { label: "Socials Button", name: "socialsButton", widget: "string" }
          - { label: "Final Book Now Button", name: "finalBookNowButton", widget: "string" }
          - { label: "Hero Image Left", name: "heroImageLeft", widget: "image" }
          - { label: "Hero Image Right", name: "heroImageRight", widget: "image" }
          - { label: "Meet The Team Image", name: "meetTheTeamImage", widget: "image" }
          - { label: "Final Gif", name: "finalGif", widget: "image" }

      - label: "About"
        name: "about"
        file: "content/pages/about.yml"
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string" }
          - { label: "Hero Text", name: "heroText", widget: "text" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }

  - name: "gallery"
    label: "About Gallery"
    folder: "content/gallery"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false, value_type: "int" }
