publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: main
local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

logo:
  src: "src/assets/logo/MONOGRAM - ONYX.svg"
  show_in_header: true

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - label: "Hero Section"
            name: "heroSection"
            widget: "object"
            fields:
              - { label: "Hero Heading", name: "heroHeading", widget: "markdown" }
              - { label: "Book Now Button", name: "bookNowButton", widget: "markdown" }
              - { label: "Hero Image Left", name: "heroImageLeft", widget: "image" }
              - { label: "Hero Image Right", name: "heroImageRight", widget: "image" }

          - label: "Intro Section"
            name: "introSection"
            widget: "object"
            fields:
              - { label: "Intro Heading", name: "introHeading", widget: "markdown" }
              - { label: "Intro Paragraph 1", name: "introParagraph1", widget: "markdown" }
              - { label: "Intro Paragraph 2", name: "introParagraph2", widget: "markdown" }
              - { label: "About Button", name: "aboutButton", widget: "markdown" }

          - label: "Meet The Team Section"
            name: "meetTeamSection"
            widget: "object"
            fields:
              - { label: "Meet The Team Heading", name: "meetTeamHeading", widget: "markdown" }
              - { label: "Meet The Team Subheading", name: "meetTeamSubHeading", widget: "markdown" }
              - { label: "Meet The Team Paragraph", name: "meetTeamParagraph", widget: "markdown" }
              - { label: "Socials Button", name: "socialsButton", widget: "markdown" }
              - { label: "Meet The Team Image", name: "meetTheTeamImage", widget: "image" }
              

          - label: "Final Slogan Section"
            name: "sloganSection"
            widget: "object"
            fields:
              - { label: "Final Slogan", name: "finalSlogan", widget: "markdown" }
              - { label: "Final Book Now Button", name: "finalBookNowButton", widget: "markdown" }
              - { label: "Final Gif", name: "finalGif", widget: "image" }
          
      - label: "About"
        name: "about"
        file: "content/pages/about.yml"
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "markdown" }
          - { label: "Hero Text", name: "heroText", widget: "markdown" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }

      - label: "Socials"
        name: "socials"
        file: "content/pages/socials.yml"
        fields:
          - label: "Faith Section"
            name: "faithSection"
            widget: "object"
            fields:
              - { label: "Faith Heading", name: "faithHeading", widget: "markdown" }
              - { label: "Faith @", name: "faithAt", widget: "text" }
              - { label: "Faith Body", name: "faithBody", widget: "markdown" }
              - { label: "Faith Image", name: "faithImage", widget: "image" }

          - label: "Erin Section"
            name: "erinSection"
            widget: "object"
            fields:
              - { label: "Erin Heading", name: "erinHeading", widget: "markdown" }
              - { label: "Erin @", name: "erinAt", widget: "text" }
              - { label: "Erin Body", name: "erinBody", widget: "markdown" }
              - { label: "Erin Image", name: "erinImage", widget: "image" }

  - name: "gallery"
    label: "About Gallery"
    folder: "content/gallery"
    create: true
    delete: true
    slug: "{{slug}}"
    summary: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false, value_type: "int" }
